#!/usr/bin/env ruby
require 'colorize'

$url = "https://lvh.me"
$arg_cacert = "--cacert output/server_ca_root_publ.crt"

puts "-------------------------------------------------------------".green
puts "--- CLIENT-1 is CURLing the server WITH cert".green
puts "--- EXPECTING SUCCESS".green
puts "-------------------------------------------------------------".green
command = [];
command.push "curl -vv"
command.push $arg_cacert
command.push "--key output/client_priv.key.nopass"
command.push "--cert output/client_publ.crt"
command.push $url
command = command.join(' ')
puts "---------------------------".green
puts "--- EXECUTING: #{command} ".green
puts "---------------------------".green
output = `#{command}`
puts output.light_blue
if(output =~ /Welcome to nginx!/i)
  puts "SUCCESS".green
else
  puts "FAIL".red
end

puts "-------------------------------------------------------------".green
puts "--- CLIENT-1 is CURLing server WITHOUT cert".green
puts "--- EXPECTING FAIL: ".green
puts "-------------------------------------------------------------".green
output = `curl #{$arg_cacert} #{$url}`
puts output.light_blue
if(output =~ /400 Bad Request/i)
  puts "SUCCESS".green
else
  puts "FAIL".red
end

puts "-------------------------------------------------------------".green
puts "--- CLIENT-2 is CURLing the server WITH fullchain".green
puts "--- EXPECTING SUCCESS".green
puts "-------------------------------------------------------------".green
command = [];
command.push "curl -vv"
command.push $arg_cacert
command.push "--key output/client2_priv.key.nopass"
command.push "--cert output/client2_publ.fullchain"
command.push $url
command = command.join(' ')
puts "---------------------------".green
puts "--- EXECUTING: #{command} ".green
puts "---------------------------".green
output = `#{command}`
puts output.light_blue
if(output =~ /Welcome to nginx!/i)
  puts "SUCCESS".green
else
  puts "FAIL".red
end
