#!/usr/bin/env ruby
require 'colorize'

$url = "https://lvh.me"

puts "-------------------------------------------------------------".green
puts "--- CLIENT1 is CURLing the server WITH cert".green
puts "--- EXPECTING SUCCESS".green
puts "-------------------------------------------------------------".green
command = [];
command.push "curl -vv"
command.push "--cacert output/server_publ.crt"
command.push "--key output/client_priv.key.nopass"
command.push "--cert output/client_publ.crt"
command.push $url
command = command.join(' ')
puts "---------------------------".green
puts "--- EXECUTING: #{command} ".green
puts "---------------------------"
output = `#{command}`
puts output.light_blue
if(output =~ /Welcome to nginx!/i)
  puts "SUCCESS".green
else
  puts "FAIL".red
end

puts "-------------------------------------------------------------".green
puts "--- CLIENT1 is CURLing server WITHOUT cert".green
puts "--- EXPECTING FAIL: ".green
puts "-------------------------------------------------------------".green
output = `curl --cacert output/server_publ.crt #{$url}`
puts output.light_blue
if(output =~ /400 Bad Request/i)
  puts "SUCCESS".green
else
  puts "FAIL".red
end