#!/usr/bin/env ruby


def die_with_error(msg)
  puts "ERROR: #{msg}"
  exit 1
end

def assert_valid_pair(publ, priv)
  # puts `openssl x509 -noout -text -in #{publ}`
  # puts `openssl rsa -noout -text -in #{priv}`
  
  publ_mod = `openssl x509 -noout -modulus -in #{publ}`
  priv_mod = `openssl rsa -noout -modulus -in #{priv}`

  puts "* PUBL_MOD = #{publ_mod}"
  puts "* PRIV_MOD = #{priv_mod}"

  if(publ_mod != priv_mod)
    die_with_error("KEY-PAIR-DOES-NOT-MATCH")
  end
end

system("./cleanup")

$bits = 1024
$enc = "-des3"

$pass = "file:inputs/passphrase.txt"
$subj = "/C=US/ST=California/L=LosAngeles/CN=lvh.me"
$subj_client = "/C=US/ST=California/L=LosAngeles/CN=client.lvh.me"
$out = "./output"

$client_ca_root_priv = "#{$out}/client_ca_root_priv.key"
$client_ca_root_publ = "#{$out}/client_ca_root_publ.crt"
$client_ca_root_priv_nopass = "#{$client_ca_root_priv}.nopass"

$server_priv = "#{$out}/server_priv.key"
$server_csr  = "#{$out}/server_csr"
$server_publ = "#{$out}/server_publ.crt"
$server_priv_nopass = "#{$server_priv}.nopass"

$client_priv = "#{$out}/client_priv.key"
$client_publ = "#{$out}/client_publ.crt"
$client_csr  = "#{$out}/client_csr"
$client_priv_nopass = "#{$client_priv}.nopass"
$client_combined_pem = "#{$out}/client_combined.pem"
$client_combined_pfx = "#{$out}/client_combined.pfx"

# Create the CA Key and Certificate for signing Client Certs
system("openssl genrsa #{$enc} -out #{$client_ca_root_priv} -passout #{$pass} #{$bits}")
system("openssl rsa -in #{$client_ca_root_priv} -out #{$client_ca_root_priv_nopass} -passin #{$pass}")
system("openssl req -new -x509 -days 365 -key #{$client_ca_root_priv} -passin #{$pass} -subj '#{$subj}' -out #{$client_ca_root_publ}")
# check CA Private <-> CA Public
assert_valid_pair($client_ca_root_publ, $client_ca_root_priv_nopass)

# Create the Server Key, CSR, and Certificate
system("openssl genrsa #{$enc} -out #{$server_priv} -passout #{$pass} #{$bits}")
system("openssl req -new -key #{$server_priv} -passin #{$pass} -subj '#{$subj}' -out #{$server_csr}")
system("openssl rsa -in #{$server_priv} -out #{$server_priv_nopass} -passin #{$pass}")
# SELF-SIGN
system("openssl x509 -req -days 365 -in #{$server_csr} -signkey #{$server_priv_nopass} -out #{$server_publ}");
# system("openssl x509 -req -days 365 -in #{$server_csr} -CA #{$client_ca_root_publ} -CAkey #{$client_ca_root_priv_nopass} -set_serial 01 -out #{$server_publ}");
assert_valid_pair($server_publ, $server_priv_nopass)

# Create the Client Key and CSR
system("openssl genrsa #{$enc} -out #{$client_priv} -passout #{$pass} #{$bits}")
system("openssl rsa -in #{$client_priv} -passin #{$pass} -out #{$client_priv_nopass}")
system("openssl req -new -key #{$client_priv_nopass} -subj #{$subj_client} -out #{$client_csr}")

# Sign the client certificate with our CA cert.
system("openssl x509 -req -days 365 -in #{$client_csr} -CA #{$client_ca_root_publ} -CAkey #{$client_ca_root_priv_nopass} -set_serial 01 -out #{$client_publ}")

system("cat #{$client_publ} #{$client_priv_nopass} > #{$client_combined_pem}")
system("openssl pkcs12 -export -out #{$client_combined_pfx} -inkey #{$client_priv_nopass} -in #{$client_publ} -certfile #{$client_ca_root_publ} -passout #{$pass}")

system("sudo systemctl restart nginx")

puts "************* Preparing to CURL"

sleep 1
puts `./curl_lvh_with_ca_crt`