#!/usr/bin/env ruby
require 'colorize'

def die_with_error(msg)
  puts "ERROR: #{msg}"
  exit 1
end

def assert_valid_pair(publ, priv)
  # puts `openssl x509 -noout -text -in #{publ}`
  # puts `openssl rsa -noout -text -in #{priv}`
  
  publ_mod = `openssl x509 -noout -modulus -in #{publ}`
  priv_mod = `openssl rsa -noout -modulus -in #{priv}`

  puts "* PUBL_MOD = #{publ_mod}"
  puts "* PRIV_MOD = #{priv_mod}"

  if(publ_mod != priv_mod)
    die_with_error("KEY-PAIR-DOES-NOT-MATCH")
  end
end

system("./cleanup")

$bits = 1024
$enc = "-des3"

$pass = "file:inputs/passphrase.txt"
$subj = "/C=US/ST=California/L=LosAngeles/CN=lvh.me"
$subj_client = "/C=US/ST=California/L=LosAngeles/CN=client.lvh.me"
$subj_intermediate = "/C=US/ST=California/L=LosAngeles/CN=intermediate.lvh.me"
$subj_client2 = "/C=US/ST=California/L=LosAngeles/CN=client2.lvh.me"
$out = "./output"

$client_ca_root_priv = "#{$out}/client_ca_root_priv.key"
$client_ca_root_publ = "#{$out}/client_ca_root_publ.crt"
$client_ca_root_priv_nopass = "#{$client_ca_root_priv}.nopass"

$server_priv = "#{$out}/server_priv.key"
$server_csr  = "#{$out}/server_csr"
$server_publ = "#{$out}/server_publ.crt"
$server_priv_nopass = "#{$server_priv}.nopass"

$client_priv = "#{$out}/client_priv.key"
$client_publ = "#{$out}/client_publ.crt"
$client_csr  = "#{$out}/client_csr"
$client_priv_nopass = "#{$client_priv}.nopass"
$client_combined_pem = "#{$out}/client_combined.pem"
$client_combined_pfx = "#{$out}/client_combined.pfx"

$intermediate_config = "./intermediate_ca.conf"
$intermediate_dir = "./output/intermediate"
$intermediate_subdirs = %w{certs crl csr newcerts private}
$intermediate_priv = "#{$intermediate_dir}/private/intermediate_priv.key"
$intermediate_priv_nopass = "#{$intermediate_dir}/private/intermediate_priv.key.nopass"
$intermediate_csr = "#{$intermediate_dir}/csr/intermediate.csr"
$intermediate_publ = "#{$intermediate_dir}/certs/intermediate_publ.crt"

$client2_priv = "#{$out}/client2_priv.key"
$client2_publ = "#{$out}/client2_publ.crt"
$client2_csr  = "#{$out}/client2_csr"
$client2_priv_nopass = "#{$client2_priv}.nopass"
$client2_combined_pem = "#{$out}/client2_combined.pem"
$client2_combined_pfx = "#{$out}/client2_combined.pfx"


# Create the CA Key and Certificate for signing Client Certs
system("openssl genrsa #{$enc} -out #{$client_ca_root_priv} -passout #{$pass} #{$bits}")
system("openssl rsa -in #{$client_ca_root_priv} -out #{$client_ca_root_priv_nopass} -passin #{$pass}")
system("openssl req -new -x509 -days 365 -key #{$client_ca_root_priv} -passin #{$pass} -subj '#{$subj}' -out #{$client_ca_root_publ}")
# check CA Private <-> CA Public
assert_valid_pair($client_ca_root_publ, $client_ca_root_priv_nopass)

# Create the Server Key, CSR, and Certificate
system("openssl genrsa #{$enc} -out #{$server_priv} -passout #{$pass} #{$bits}")
system("openssl req -new -key #{$server_priv} -passin #{$pass} -subj '#{$subj}' -out #{$server_csr}")
system("openssl rsa -in #{$server_priv} -out #{$server_priv_nopass} -passin #{$pass}")
# SELF-SIGN
system("openssl x509 -req -days 365 -in #{$server_csr} -signkey #{$server_priv_nopass} -out #{$server_publ}");
# system("openssl x509 -req -days 365 -in #{$server_csr} -CA #{$client_ca_root_publ} -CAkey #{$client_ca_root_priv_nopass} -set_serial 01 -out #{$server_publ}");
assert_valid_pair($server_publ, $server_priv_nopass)


#---------------------------------------------------------------------------------------------
#--- CREATE CLIENT 1
#---------------------------------------------------------------------------------------------
# Create the Client Key and CSR
system("openssl genrsa #{$enc} -out #{$client_priv} -passout #{$pass} #{$bits}")
system("openssl rsa -in #{$client_priv} -passin #{$pass} -out #{$client_priv_nopass}")
system("openssl req -new -key #{$client_priv_nopass} -subj #{$subj_client} -out #{$client_csr}")

# Sign the client certificate with our CA cert.
system("openssl x509 -req -days 365 -in #{$client_csr} -CA #{$client_ca_root_publ} -CAkey #{$client_ca_root_priv_nopass} -set_serial 01 -out #{$client_publ}")

system("cat #{$client_publ} #{$client_priv_nopass} > #{$client_combined_pem}")
system("openssl pkcs12 -export -out #{$client_combined_pfx} -inkey #{$client_priv_nopass} -in #{$client_publ} -certfile #{$client_ca_root_publ} -passout #{$pass}")


# Create Intermediate
puts "********** GENERATING INTERMEDIATE".red
system("mkdir -p #{$intermediate_dir}")
$intermediate_subdirs.each do |dir|
  system("mkdir -p #{$intermediate_dir}/#{dir}")
end
system("echo 1000 > #{$intermediate_dir}/serial")
system("echo 1000 > #{$intermediate_dir}/crlnumber")

system("openssl genrsa #{$enc} -out #{$intermediate_priv} -passout #{$pass} #{$bits}")
system("openssl rsa -in #{$intermediate_priv} -out #{$intermediate_priv_nopass} -passin #{$pass}")
system("openssl req -config #{$intermediate_config} -new -sha256 -key #{$intermediate_priv_nopass} -subj '#{$subj_intermediate}' -passout #{$pass} -out #{$intermediate_csr}")

puts "************************* DONE GENERATING INTERMEDIATE".red
# system("openssl req -new -sha256 -key #{$client_priv_nopass} -subj '#{$subj_intermediate}' -out #{$intermediate_csr}")
# puts `openssl ca -extensions v3_intermediate_ca -days 365 -notext -md sha256 -in #{$intermediate_csr} -out #{$intermediate_crt}`
#---------------------------------------------------------------------------------------------
#--- CREATE CLIENT 2
#---------------------------------------------------------------------------------------------
system("openssl genrsa #{$enc} -out #{$client2_priv} -passout #{$pass} #{$bits}")
system("openssl rsa -in #{$client2_priv} -passin #{$pass} -out #{$client2_priv_nopass}")
system("openssl req -new -key #{$client2_priv_nopass} -subj #{$subj_client2} -out #{$client2_csr}")

# Sign the client certificate with client's CA
system("openssl x509 -req -days 365 -in #{$client2_csr} -CA #{$client_publ} -CAkey #{$client_priv_nopass} -set_serial 01 -out #{$client2_publ}")


system("cat #{$client2_publ} #{$client2_priv_nopass} > #{$client2_combined_pem}")
system("openssl pkcs12 -export -out #{$client2_combined_pfx} -inkey #{$client2_priv_nopass} -in #{$client2_publ} -certfile #{$client_publ} -passout #{$pass}")


system("sudo systemctl restart nginx")
puts "************* Preparing TESTS. SLEEPING...".green
sleep 1
puts `./curl_lvh_with_ca_crt`